# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Internet Computer Improvement Proposals
description: >-
  Internet Computer Improvement Proposals (ICIPs) describe changes to Internet Computer including
  intents, standards, and positions.
url: "https://ICIPs.dfinity.org"
github_username: dfinity

header_pages:
 - all.html
 - informational.html
 - standard.html
 - meta.html

# Build settings
highlighter: rouge
markdown: kramdown
theme: minima
kramdown:
  parse_block_html: false
  auto_ids: true
  auto_id_stripping: true
  syntax_highlighter: rouge

permalink: /:slug

defaults:
  -
    scope:
      path: "ICIPS"
    values:
      layout: "ICIP"

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ICIP-template.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
